CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(10)  NOT NULL,
    balance_minor  BIGINT       NOT NULL,
    currency       VARCHAR(255) NOT NULL,
    customer_id    BIGINT       NOT NULL,
    version        BIGINT       NOT NULL,
    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT accounts_currency_check CHECK (currency IN ('NGN', 'USD'))
);

CREATE TABLE ledger_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255) NOT NULL,
    amount_minor   BIGINT       NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    currency       VARCHAR(255) NOT NULL,
    reference      VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    CONSTRAINT ledger_entries_currency_check CHECK (currency IN ('NGN', 'USD')),
    CONSTRAINT ledger_entries_type_check CHECK (type IN ('DEBIT', 'CREDIT'))
);

CREATE TABLE transfers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_minor        BIGINT       NOT NULL,
    bank_code           VARCHAR(255),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    currency            VARCHAR(255) NOT NULL,
    destination_account VARCHAR(255) NOT NULL,
    failure_reason      VARCHAR(500),
    idempotency_key     VARCHAR(255) NOT NULL,
    provider_reference  VARCHAR(255),
    reference           VARCHAR(255) NOT NULL,
    source_account      VARCHAR(255) NOT NULL,
    status              VARCHAR(255) NOT NULL,
    CONSTRAINT uq_transfers_reference UNIQUE (reference),
    CONSTRAINT uq_transfers_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT transfers_currency_check CHECK (currency IN ('NGN', 'USD')),
    CONSTRAINT transfers_status_check CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);
